use_default_settings: true

server:
  secret_key: "replace-in-production"
  limiter: false
  image_proxy: true

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "auto"

ui:
  static_use_hash: true

