use_default_settings: true

server:
  secret_key: "replace-in-production"
  limiter: false
  image_proxy: true

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "auto"
  formats:
    - html
    - json

ui:
  static_use_hash: true

outgoing:
  extra_proxy_timeout: 10
  proxies:
    all://:
      - http://host.docker.internal:17890

engines:
  - name: bing
    disabled: false
  - name: mojeek
    disabled: false
  - name: brave
    disabled: true
  - name: duckduckgo
    disabled: true
  - name: google
    disabled: true
  - name: karmasearch
    disabled: true
  - name: karmasearch videos
    disabled: true
  - name: startpage
    disabled: true
